name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup relay
        run: docker compose up -d --wait
        working-directory: test
      - run: npm ci
      - run: npm test
